pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker build ./WorldOfGames/ -t jenmar/flaskapp:v1'
            }
        }
        stage('Run docker build') {
            steps {
                sh 'docker run -d -p 4444:4444 --name chrome-driver selenium/standalone-chrome'
                sh 'docker run -d -p 8777 -v $(pwd)/Scores.txt:/root/app/Scores.txt --name my-flask-test3 jenmar/flaskapp:v1'
            }
        }
        stage('Run tests') {
            steps {
                sh 'python3 ./WorldOfGames/Tests/e2e.py'
            }
        }
    }
    post {
        always {
            sh "docker stop my-flask-test3"
            sh "docker stop chrome-driver"
            sh "docker rm my-flask-test3"
            sh "docker rm chrome-driver"
        }
    }
}