pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Push to Dockerhub') {
            steps {
               withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                    sh "docker build -t jenmar/flaskapp:latest ./WorldOfGames/"
                    sh "docker push jenmar/flaskapp:latest"
               }
            }
        }
        stage('Run docker build') {
            steps {
                sh 'docker run -d -p 8777 -v $(pwd)/Scores.txt:/root/app/Scores.txt --name my-flask-test jenmar/flaskapp:latest'
            }
        }
        stage('Run tests') {
            steps {
                sh 'python3 ./WorldOfGames/Tests/e2e.py'
            }
        }
    }
    post {
        always {
            sh "docker stop my-flask-test"
            sh "docker rm my-flask-test"
        }
    }
}